image: 'docker:stable'
services:
  - 'docker:dind'
variables:
  IMAGE_NAME: transmission-daemon
  REGISTRY_URL: registry.gitlab.com
  CONTAINER_IMAGE: $REGISTRY_URL/$CI_PROJECT_NAMESPACE/$IMAGE_NAME
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: 'tcp://docker:2375'
  DOCKER_USER: gitlab-ci-token
before_script:
  - docker login -u $DOCKER_USER -p $CI_JOB_TOKEN $REGISTRY_URL
build:
  only: master
  stage: build
  script:
    - 'docker pull $CONTAINER_IMAGE:latest || true'
    - >-
      docker build --cache-from $CONTAINER_IMAGE:latest --tag
      $CONTAINER_IMAGE:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE:latest .
    - 'docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA'
    - 'docker push $CONTAINER_IMAGE:latest'
