image: 'docker:stable'
services:
  - 'docker:dind'
variables:
  IMAGE_NAME: transmission-daemon
  IMAGE_URL: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$IMAGE_NAME
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: 'tcp://docker:2375'
before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
build:
  only:
    - master
  stage: build
  script:
    - 'docker pull $IMAGE_URL:latest || true'
    - >-
      docker build --cache-from $IMAGE_URL:latest --tag
      $IMAGE_URL:$CI_COMMIT_SHA --tag $IMAGE_URL:latest .
    - 'docker push $IMAGE_URL:$CI_COMMIT_SHA'
    - 'docker push $IMAGE_URL:latest'
